@startuml GestorTarea
actor User

participant "GestorTarea" as GT
participant "Tarea" as T
participant "AlgoritmoOrdenamiento" as AO
participant "AlgoritmoBusqueda" as AB
participant "BuscadorParam" as BP

User -> GT: Crear GestorTarea
GT -> GT: Constructor()
note right of GT: Inicializa tarea = []

User -> GT: agregarTarea(t: Tarea)
GT -> GT: this.tarea.push(t)

User -> GT: getTareas()
GT -> GT: return this.tarea

User -> GT: ordenarTarea(a: AlgoritmoOrdenamiento)
GT -> AO: ordenar(this.tarea)

User -> GT: buscarTarea(a: AlgoritmoBusqueda, param: BuscadorParam)
GT -> AB: buscar(this.tarea, param)
AB -> GT: return resultados

@enduml