@startuml Diagrama

class Tarea {
    -titulo: string
    -descripcion: string 
    -fechaDeVencimiento: Date
    -nivelPrioridad: number
    -categoria: enum
    -prograso: number
    -etiqueta:string  
}

class GestorTarea {
    -tareaPendiente : Array<Tarea>
    -tareaFinalizada: Array<Tarea>
    +aniadir(t:tarea)
    +eliminar(t:tarea)
      
}

interface Buscar {
  buscador(dato<T>):Tarea
}

interface Ordenar {
  ordenarTitulo(s:string):void
}

class Usuario {
    -nombre: string
    -gestor: GestorTarea  
}

Usuario *--- GestorTarea
GestorTarea *--- Tarea
GestorTarea *--- Buscar
GestorTarea *--- Ordenar
@enduml