@startuml AppTareas

enum Prioridad {
    ALTA
    MEDIA
    BAJA
}

enum Categoria {
    TRABAJO
    PERSONAL
    RECADOS
}

enum EstadoTarea {
    PENDIENTE
    COMPLETADA
}

interface EditarTareaParam {
    titulo?:string
    descripcion?:string
    fechaVencimiento?:Date
    prioridad?:Prioridad
    progreso?:number
    tiempoDedicado?:number
}

class Tarea {
    -id: number
    -titulo: string
    -descripcion: string
    -fechaVencimiento: Date
    -prioridad: Prioridad
    -estado: EstadoTarea
    -progreso: number
    -categoria: Categoria
    -etiquetas:Array<Etiqueta>
    -tiempoDedicado:number

    +editarTarea(params:EditarTareaParams):void
    +agregarEtiqueta(e:Etiqueta):void 
}


class GestorTareas {
    -tareas:Array<Tarea>

    +crearTarea():Tarea
    +agregarTarea(t: Tarea):void
    +eliminarTarea(t:Tarea):void
    +buscarTarea(t:Tarea, a:AlgoritmoBusqueda):Tarea[]
    +ordenarTareas(a:AlgoritmoOrdenamiento):void
    +obtenerEstadisticas(e:Estadistica): Estadistica
}

interface AlgoritmoBusqueda {
    <i>buscar(t:Array<Tarea>, param:BuscadorParam):Tarea[]
}

class BusquedaTitulo implements AlgoritmoBusqueda{
    +buscar(t:Array<Tarea>, param:BuscadorParam):Tarea[]
}

class BusquedaFecha implements AlgoritmoBusqueda{
    +buscar(t:Array<Tarea>, param:BuscadorParam):Tarea[]
}

interface BuscadorParam {
    titulo?:string
    fecha?:Date
}

interface AlgoritmoOrdenamiento {
    <i>ordenar(t:Array<Tarea>):void
}

class OrdenFecha implements AlgoritmoOrdenamiento{
    +ordenar(t:Array<Tarea>):void
}

class OrdenTitulo implements AlgoritmoOrdenamiento{
    +ordenar(t:Array<Tarea>):void
}

class OrdenPrioridad implements AlgoritmoOrdenamiento{
    +ordenar(t:Array<Tarea>):void
}

class Etiqueta {
    -nombre: string
}

class Estadistica {
    -tareasCompletadas:Array<Tarea>
    -tareasPendientes:Array<Tarea>
    -tiempoPromedio:number
    -tasaFinalizacion:number

    +calcularEstadisticas(tareas:Array<Tarea>):Estadistica
    +listadoTareasCompletas(tareas:Array<Tarea>):Array<Tarea>
    +listadoTareasPendientes(tareas:Array<Tarea>):Array<Tarea>
    +calcularPromedioTiempo(tareas:Array<Tarea>):number
    +calcularTasaFinalizacion(tareas:Array<Tarea>):number
}

Tarea --> Categoria
Tarea *-- Etiqueta
GestorTareas *.. Tarea
GestorTareas <--u Estadistica
Tarea --> Prioridad
Tarea --> EstadoTarea
GestorTareas <---r AlgoritmoOrdenamiento
GestorTareas <--l AlgoritmoBusqueda
Tarea<..l EditarTareaParam
BuscadorParam --> AlgoritmoBusqueda
@enduml
